// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SheldureUnit.Server.Data;

#nullable disable

namespace SheldureUnit.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240408104827_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SheldureUnit.Server.Data.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Classroom 101",
                            Name = "Classroom 101"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Classroom 102",
                            Name = "Classroom 102"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Classroom 103",
                            Name = "Classroom 103"
                        });
                });

            modelBuilder.Entity("SheldureUnit.Server.Data.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("FirstClassRoomId")
                        .HasColumnType("int");

                    b.Property<string>("FirstLessonType")
                        .HasColumnType("longtext");

                    b.Property<int?>("FirstSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondClassRoomId")
                        .HasColumnType("int");

                    b.Property<string>("SecondLessonType")
                        .HasColumnType("longtext");

                    b.Property<int?>("SecondSubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirstClassRoomId");

                    b.HasIndex("FirstSubjectId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SecondClassRoomId");

                    b.HasIndex("SecondSubjectId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = 0,
                            FirstClassRoomId = 1,
                            FirstLessonType = "Lecture",
                            FirstSubjectId = 1,
                            Number = 1,
                            ScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Day = 0,
                            FirstClassRoomId = 2,
                            FirstLessonType = "Lab",
                            FirstSubjectId = 2,
                            Number = 2,
                            ScheduleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Day = 1,
                            FirstClassRoomId = 3,
                            FirstLessonType = "Lecture",
                            FirstSubjectId = 3,
                            Number = 1,
                            ScheduleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Day = 1,
                            FirstClassRoomId = 1,
                            FirstLessonType = "Lab",
                            FirstSubjectId = 4,
                            Number = 2,
                            ScheduleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Day = 2,
                            FirstClassRoomId = 2,
                            FirstLessonType = "Lab",
                            FirstSubjectId = 1,
                            Number = 1,
                            ScheduleId = 1,
                            SecondClassRoomId = 3,
                            SecondLessonType = "Lecture",
                            SecondSubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            Day = 2,
                            FirstClassRoomId = 3,
                            FirstLessonType = "Lecture",
                            FirstSubjectId = 3,
                            Number = 2,
                            ScheduleId = 1,
                            SecondClassRoomId = 1,
                            SecondLessonType = "Lab",
                            SecondSubjectId = 4
                        });
                });

            modelBuilder.Entity("SheldureUnit.Server.Data.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = "1 hour",
                            Group = "Group A",
                            Name = "Schedule for Group A"
                        });
                });

            modelBuilder.Entity("SheldureUnit.Server.Data.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectDescription = "Description for Mathematics",
                            SubjectName = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            SubjectDescription = "Description for Science",
                            SubjectName = "Science"
                        },
                        new
                        {
                            Id = 3,
                            SubjectDescription = "Description for History",
                            SubjectName = "History"
                        },
                        new
                        {
                            Id = 4,
                            SubjectDescription = "Description for Literature",
                            SubjectName = "Literature"
                        });
                });

            modelBuilder.Entity("SheldureUnit.Server.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SheldureUnit.Server.Data.Lesson", b =>
                {
                    b.HasOne("SheldureUnit.Server.Data.ClassRoom", "FirstClassRoom")
                        .WithMany()
                        .HasForeignKey("FirstClassRoomId");

                    b.HasOne("SheldureUnit.Server.Data.Subject", "FirstSubject")
                        .WithMany()
                        .HasForeignKey("FirstSubjectId");

                    b.HasOne("SheldureUnit.Server.Data.Schedule", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheldureUnit.Server.Data.ClassRoom", "SecondClassRoom")
                        .WithMany()
                        .HasForeignKey("SecondClassRoomId");

                    b.HasOne("SheldureUnit.Server.Data.Subject", "SecondSubject")
                        .WithMany()
                        .HasForeignKey("SecondSubjectId");

                    b.Navigation("FirstClassRoom");

                    b.Navigation("FirstSubject");

                    b.Navigation("SecondClassRoom");

                    b.Navigation("SecondSubject");
                });

            modelBuilder.Entity("SheldureUnit.Server.Data.Schedule", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
